server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos地址
      discovery:
        namespace: 0ce710fd-9196-49df-8353-9045c396534e
        group: dev
    gateway:
      routes:
        - id: user-service # 路由标识，必须唯一
          uri: lb://userService # 路由的目标地址
          predicates:
            - Path=/sys/user/** # 路径断言，判断路径是否以/user开头
          filters:
          - AddRequestHeader=Truth,ItHeibai is freaking awesome! # 添加请求头，局部过滤器(路由过滤器)
        - id: order-service # 路由标识，必须唯一
          uri: lb://orderService # 路由的目标地址
          predicates:
              - Path=/sys/order/** # 路径断言，判断路径是否以/user开头
      default-filters:
        - AddRequestHeader=Truth,ItHeibai is freaking awesome! #默认全局过滤器

      # 过滤器执行顺序:
      # default-filters > 路由过滤器 > GlobalFilter

      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决 options 请求被拦截的问题
        cors-configurations:
          '[/**]':
           allowedOrigins: # 允许哪些网站的跨域请求
             - "http://localhost:63343"
             - "https://www.itheibai.com"
           allowedMethods: #允许的跨域ajax的请求方式
             - "GET"
             - "POST"
             - "DELETE"
             - "PUT"
             - "OPTIONS"
           allowedHeaders: "*" # 允许在请求中携带的头信息
           allowCredentials: true # 是否允许携带cookie
           maxAge: 360000 # 这次跨域检测的有效期